### ISSUE TITLE
Klipper Config and Slicer Settings

### ISSUE THREAD

**Issue by zimmra** [sashalex007/speedDrive#1]
Hoping to get a bit more insight on specific acceleration levels and speeds you've had success with in your Klipper config and your slicer settings. 

Are the default Klipper settings for the Ender 3 okay to leave as is?

```
[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100
```

You mentioned 100mm/s and 1000mm/s<sup>2</sup> acceleration. Are you just doing that flat across the board, or are you tweaking it for outer layers/first layer/etc?

The files themselves printed as intended and all seems to fit just fine, now just looking to dial in the software.

**Comment by sashalex007** [comment]
Those settings look OK. TBH, I have not yet messed around with newer versions of klipper so you can consider my knowledge out of date. At the time that speed drive was created, the speeds I was running were almost unheard of for ender 3. Now with input shaping and other features I think speeds and accelerations can be pushed alot higher with no loss in quality. I would check out the klipper discord for expert software tuning.
