### ISSUE TITLE
fan mount for speed drive with BLTOUCH

### ISSUE THREAD

**Issue by Leygan1** [sashalex007/speedDrive#5]
hello, i am using speedDrive_heromeBase_bltouch_combined.stl

What fan can I add for part cooling? I have problems with printing without fan :(

**Comment by Leygan1** [comment]
nothing?

**Comment by sashalex007** [comment]
Sorry for the late reply. I use [this duct](https://www.thingiverse.com/thing:3779498/files), on the right side.
